### PR TITLE
Add screenshots controller for CRUD operations

### PR DESCRIPTION
**Pull request by tpardeshi**

### CODE REVIEW

**Comment by rahulbajaj0509** [comment]
Can you please resolve all the conflicts from this and the other PR so that I can review the PR's. If you are not confirtable in resolving the conflicts please reach out to me.

**Comment by tpardeshi** [comment]
Ok. I will try resolving it.

**Comment by tpardeshi** [comment]
Conflicts resolved.

**Comment by rahulbajaj0509** [comment]
It still shows conflicts!

**Comment by tpardeshi** [comment]
From my side I see no conflicts. It says "This branch has no conflicts with the base branch".

**Comment by rahulbajaj0509** [comment]
It looks there is something wrong, on GitHub I see 'This branch cannot be rebased due to conflicts'. Do you see the same?

**Comment by tpardeshi** [comment]
No the same is not seen from my side.  Actually we have 2 PRs open and both the PRs have few same files been changed. Is it because of this reason? If so we can close one PR for now. Because both the PRs are doing the same job of file upload but with different approach. 

- First approach: Using service for image upload(PR: Image controller added)
- Second approach: Using CURD in screenshots controller for image upload (PR: Add screenshots controller for CRUD operations)

**Comment by rahulbajaj0509** [comment]
> No the same is not seen from my side. Actually we have 2 PRs open and both the PRs have few same files been changed. Is it because of this reason? If so we can close one PR for now. Because both the PRs are doing the same job of file upload but with different approach.

Nope, conflicts are always checked with the master branch and not within the open PRs.  You  need to clear conflicts using git. https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line
> 
>     * First approach: Using service for image upload(PR: Image controller added)
> 
>     * Second approach: Using CURD in screenshots controller for image upload (PR: Add screenshots controller for CRUD operations)

Let me know if you are still stuggling with this.

**Comment by rahulbajaj0509** [comment]
So now everything is boiled down to 4 files, open each of these files and resolve the conflicts for these files :) Let me know if anything is required!

**Comment by tpardeshi** [comment]
Will open a new PR for the same due to some conflicts issue.

**Pull request closed without merging**
