### PR TITLE
Add Locales API

### PR DESCRIPTION
**Pull request by tpardeshi**

### CODE REVIEW

**Comment by rahulbajaj0509** [comment]
LGTM! @sourabh-upadhyay @aaditi-jain  please review at your convenience :)

**Comment by sourabh-upadhyay** [comment]
Rebase required otherwise LGTM!

**Comment by tpardeshi** [comment]
Conflicts resolved. Please review and merge.

**Comment by tpardeshi** [comment]
Conflicts solved. Please check.

**Comment by tpardeshi** [comment]
Removed middleware configuration(cors). Please review and merge.

**Comment by rahulbajaj0509** [comment]
@tpardeshi looks good to me! thanks.

Merging :+1:

**Pull request merged**
